Repository matrix-org/sliding-sync, pull requests merged in 2023-08, with the labels that each got.

#235 Do not make snapshots for lone leave events
  pubsub/v2.go
  state/accumulator.go
  state/accumulator_test.go
  state/storage.go
  state/storage_test.go
  sync2/handler2/handler.go
  sync2/poller.go
  sync2/poller_test.go
  sync3/caches/global_test.go
  sync3/caches/update.go
  sync3/caches/user.go
  sync3/handler/connstate_live.go
  sync3/handler/handler.go
  tests-e2e/security_test.go
Labels: bug

#237 Suppress duplicate account data events
  sync2/handler2/handler.go
  tests-e2e/account_data_test.go
  tests-e2e/main_test.go
Labels: bug, poller

#246 Optimise upsert queries for device data
  state/device_data_table.go
  state/device_data_table_test.go
Labels: bug

#264 Improve performace when getting room state after event position
  state/storage.go
  sync3/dispatcher.go
  sync3/handler/connstate.go
  sync3/handler/connstate_test.go
  sync3/tracker.go
  sync3/tracker_test.go
Labels: performance

#269 OTLP not Jaeger
  cmd/syncv3/main.go
  go.mod
  go.sum
  internal/trace.go
Labels: enhancement

#276 Increase the number of user IDs allowed in device list changes
  state/device_data_table.go
Labels: bug
